### ISSUE TITLE
Add special styling for spoiler callouts

### ISSUE THREAD

**Issue by zkat** [cwegrzyn/obsidian-forged#33]
We should do spoilers like this:

```markdown
> [!spoiler]- Spoiler Title
> Spoiler content
```

and then style them...

```css
.callout[data-callout="spoiler"] {
    --callout-icon: 'svg blah blah blah';
    --callout-color: some color var or literal;
}
```
